# Scheduler settings
queue: normal
ncpus: 16
walltime: 1:00:00
mem: 64GB
jobname: crujra_accessN96_1h

# Model settings
model: cable
exe: /home/189/sb8430/cable/trunk/offline/cable-mpi # cable trunk (last changed revision: 9469):
input:
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/LWdown
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/PSurf
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/Qair
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/Rainf
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/Snowf
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/SWdown
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/Tair
    - /g/data/rp23/data/no_provenance/met_forcing/crujra_accessN96_1h/Wind
    - /g/data/rp23/data/no_provenance/landmask/crujra_accessN96_landmask.nc
    - /g/data/rp23/data/no_provenance/gridinfo/crujra_accessN96_gridinfo.nc
    - ./auxillary_inputs/modis_phenology_csiro_13evergreen.txt
    - ./auxillary_inputs/pftlookup.csv

userscripts:
  setup: ./userscripts/read_casa_restart.sh

# Disable collation
collate: False

# The walltime time used for one run ~ 3 minutes
runspersub: 10

